* This repository helps to set up my build enviroment
  
  The whole setup is based on [[https://github.com/pfultz2/cget][cget]]. You can install cget with =pip3 install cget=.

* Normal build enviroment

  Just copy this repository to =~/local= and set up environment variables in =.profile= as
  #+BEGIN_SRC bash
    export PATH=${HOME}/local/bin:$PATH
    export LD_LIBRARY_PATH=${HOME}/local/lib:$LD_LIBRARY_PATH

    export CGET_PREFIX=${HOME}/local
  #+END_SRC
  Now you can easily install packages, e.g. to install the latest version of [[https://github.com/mosra/magnum][Magnum]] you just run =$ cget install magnum=.

* Emscripten build enviroment

  1. You should start by installing [[https://github.com/kripken/emscripten][Emscripten]] by following the install instructions therein. 

  2. Set up environmental variable =EMSCRIPTEN= to the Emscripten installation directory. For example by adding =export EMSCRIPTEN=some path/emsdk/emscripten/1.37.36= to your =.profile=

  3. Now you have two options, either to a set up for Wasm or Asm.js

  3a. WebAssembly 

  Create directory for the new build environment:
  #+BEGIN_SRC bash
    mkdir ~/wasm-local && cd ~/wasm-local
  #+END_SRC

  Copy the repository to this directory
  #+BEGIN_SRC bash
    git init; git remote add origin git@github.com:lecopivo/my-cget-recipes.git; git pull origin master;
  #+END_SRC

  Initialize =cget=
  #+BEGIN_SRC bash
    cget init --prefix ${EMSCRIPTEN}/system --toolchain ./etc/toolchains/generic/Emscripten-wasm.cmake
  #+END_SRC


  3b. Asm.js: Initialize =cget=.

  Create directory for the new build environment:
  #+BEGIN_SRC bash
    mkdir ~/asm.js-local && cd ~/asm.js-local
  #+END_SRC

  Copy the repository to this directory
  #+BEGIN_SRC bash
    git init; git remote add origin git@github.com:lecopivo/my-cget-recipes.git; git pull origin master;
  #+END_SRC

  Initialize =cget=
  #+BEGIN_SRC bash
    cget init --prefix ${EMSCRIPTEN}/system --toolchain ./etc/toolchains/generic/Emscripten.cmake
  #+END_SRC

* Package Installation

  NOTE: All the following examples are for environment =~/wasm-local/=, change
  the directory to the appropriate directory.
  
  To install package:
  #+BEGIN_SRC bash
     cget --prefix ~/wasm-local install magnum
  #+END_SRC

* Building project with in an environment

  NOTE: All the following examples are for environment =~/wasm-local/=, change
  the directory to the appropriate directory.

  To run cmake for specific build environment just supply appropriate
  toolchain file
  #+BEGIN_SRC bash
     cmake .. -DCMAKE_TOOLCHAIN_FILE=~/wasm-local/cget/cget.cmake
  #+END_SRC

  Or in the directory where =CMakeLists.txt= exists run 
  #+BEGIN_SRC bash
     ~/wasm-local/bin/configure-build 
  #+END_SRC
  


